config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  # admin
  namespace :admin do
    resources :dashboard
    resources :events
    resources :settings, only: %i[index]
    scope 'stripe', as: :stripe do
      controller :stripe_connect do
        get :account_setup
      end
    end
  end

  # org pages
  scope "/:organization_name", :as => "organization" do
    controller :registration_dashboard do 
      get '/', action: :dashboard
    end
    scope "/:event_url", :as => "event" do
      controller :events do
        get '/', action: :index
      end
    end
  end
end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < ApplicationController
  layout 'admin'
  def index; end
end

app/helpers/admin/setting_helper.rb
module Admin::SettingHelper
end

app/views/admin/settings/index.html.erb
<div class="h-screen overflow-hidden flex">

  <!-- Content area -->
  <div class="flex-1 flex flex-col">
    <div class="flex-1 overflow-y-auto focus:outline-none">
      <div class="relative max-w-5xl mx-auto md:px-8 xl:px-0">
        <div class="pt-10 pb-16">
          <div class="px-4 sm:px-6 md:px-0">
            <h1 class="text-3xl font-extrabold text-gray-900">Settings</h1>
          </div>
          <div class="bg-white rounded-lg mt-4 px-4 sm:px-6 md:px-0">
            <div class="p-6">
              <!-- Tabs -->
              <div class="lg:hidden">
                <label for="selected-tab" class="sr-only">Select a tab</label>
                <select id="selected-tab" name="selected-tab" class="mt-1 block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-purple-500 focus:border-purple-500 sm:text-sm rounded-md">
                  <option selected>General</option>
                  <option>Team Members</option>
                </select>
              </div>
              <div class="hidden lg:block">
                <div class="border-b border-gray-200">
                  <nav class="-mb-px flex space-x-8">
                    <!-- Current: "border-purple-500 text-purple-600", Default: "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700" -->
                    <a href="#" class="border-purple-500 text-purple-600 whitespace-nowrap py-4 px-1 border-b-2 font-medium text-sm">
                      General
                    </a>

                    <%
=begin%>
 <a href="#" class="border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 whitespace-nowrap py-4 px-1 border-b-2 font-medium text-sm">
                      Password
                    </a> 
<%
=end%>
                  </nav>
                </div>
              </div>

              <!-- Description list with inline editing -->
              <div class="mt-10 divide-y divide-gray-200">
                <div class="space-y-1">
                  <h3 class="text-lg leading-6 font-medium text-gray-900">
                    Council Information
                  </h3>
                  <p class="max-w-2xl text-sm text-gray-500">
                    This information will be displayed publicly so be careful what you share.
                  </p>
                </div>
                <div class="mt-6">
                  <dl class="divide-y divide-gray-200">
                    <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4">
                      <dt class="text-sm font-medium text-gray-500">
                        Name
                      </dt>
                      <dd class="mt-1 flex text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                        <span class="flex-grow"><%= current_user.organization.name %></span>
                        <span class="ml-4 flex-shrink-0">
                          <button type="button" class="bg-white rounded-md font-medium text-purple-600 hover:text-purple-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500">
                            Update
                          </button>
                        </span>
                      </dd>
                    </div>
                    <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:pt-5">
                      <dt class="text-sm font-medium text-gray-500">
                        Photo
                      </dt>
                      <dd class="mt-1 flex text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                        <span class="flex-grow">
                          <img class="h-8 w-8 rounded-full" src="https://images.unsplash.com/photo-1550525811-e5869dd03032?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
                        </span>
                        <span class="ml-4 flex-shrink-0 flex items-start space-x-4">
                          <button type="button" class="bg-white rounded-md font-medium text-purple-600 hover:text-purple-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500">
                            Update
                          </button>
                          <span class="text-gray-300" aria-hidden="true">|</span>
                          <button type="button" class="bg-white rounded-md font-medium text-purple-600 hover:text-purple-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500">
                            Remove
                          </button>
                        </span>
                      </dd>
                    </div>
                  </dl>
                </div>
              </div>

              <div class="mt-10 divide-y divide-gray-200">
                <div class="space-y-1">
                  <h3 class="text-lg leading-6 font-medium text-gray-900">
                    Account
                  </h3>
                  <p class="max-w-2xl text-sm text-gray-500">
                    Manage how information is displayed on your account.
                  </p>
                </div>
                <div class="mt-6">
                  <dl class="divide-y divide-gray-200">
                    <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4">
                      <dt class="text-sm font-medium text-gray-500">
                        Payments
                      </dt>
                      <dd class="mt-1 flex text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                        <span class="flex-grow">English</span>
                        <span class="ml-4 flex-shrink-0">
				                  <%= link_to "Manage Payments", admin_stripe_account_setup_path, class: "rounded-md font-medium text-purple-600 hover:text-purple-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500" %>
                        </span>
                      </dd>
                    </div>
                  </dl>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>